name=SXPCom
version=0.0.1
author=Sideways Experiments
maintainer=Sideways Experiments <dev@side-xp.com>
sentence=A library for using the SXPCom protocol
paragraph=A library for using the SXPCom protocol to turn the Serial port into a production-ready communication system.
category=Communication
url=https://github.com/side-xp/arduino-sxpcom
architectures=*